Using worker: worker-linux-docker-54af01d0.prod.travis-ci.org:travis-linux-13
Build system information
Build language: node_js
Build group: stable
Build dist: precise
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ export DEBIAN_FRONTEND=noninteractive
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 36669 36677
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-i386_Packages.gz is not what the server reported 36729 36733
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libc-bin libc-dev-bin libc6-dev
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc-bin libc-dev-bin libc6 libc6-dev
4 upgraded, 0 newly installed, 0 to remove and 209 not upgraded.
Need to get 8,844 kB of archives.
After this operation, 9,216 B disk space will be freed.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.13 [2,943 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-dev-bin amd64 2.15-0ubuntu10.13 [84.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-bin amd64 2.15-0ubuntu10.13 [1,179 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6 amd64 2.15-0ubuntu10.13 [4,637 kB]
Fetched 8,844 kB in 0s (33.5 MB/s)
Preconfiguring packages ...
(Reading database ... 69991 files and directories currently installed.)
Preparing to replace libc6-dev 2.15-0ubuntu10.10 (using .../libc6-dev_2.15-0ubuntu10.13_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10.10 (using .../libc-dev-bin_2.15-0ubuntu10.13_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libc-bin 2.15-0ubuntu10.10 (using .../libc-bin_2.15-0ubuntu10.13_amd64.deb) ...
Unpacking replacement libc-bin ...
Processing triggers for man-db ...
Setting up libc-bin (2.15-0ubuntu10.13) ...
(Reading database ... 69991 files and directories currently installed.)
Preparing to replace libc6 2.15-0ubuntu10.10 (using .../libc6_2.15-0ubuntu10.13_amd64.deb) ...
Unpacking replacement libc6 ...
Setting up libc6 (2.15-0ubuntu10.13) ...
Setting up libc-dev-bin (2.15-0ubuntu10.13) ...
Setting up libc6-dev (2.15-0ubuntu10.13) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
$ git clone --depth=50 https://github.com/urfu-2015/webdev-tasks-2.git urfu-2015/webdev-tasks-2
Cloning into 'urfu-2015/webdev-tasks-2'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.

$ cd urfu-2015/webdev-tasks-2
$ git fetch origin +refs/pull/16/merge:
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 15 (delta 5), reused 11 (delta 2), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/urfu-2015/webdev-tasks-2
 * branch            refs/pull/16/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
$ nvm install stable
######################################################################## 100.0%
Checksums empty
Now using node v5.6.0

$ node --version
v5.6.0
$ npm --version
3.6.0
$ nvm --version
0.23.3
$ npm install
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
/home/travis/build/urfu-2015/webdev-tasks-2
├─┬ assert@1.3.0
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
├─┬ jscs@2.2.1
│ ├─┬ babel-core@5.8.35
│ │ ├── babel-plugin-constant-folding@1.0.1
│ │ ├── babel-plugin-dead-code-elimination@1.0.2
│ │ ├── babel-plugin-eval@1.0.1
│ │ ├── babel-plugin-inline-environment-variables@1.0.1
│ │ ├── babel-plugin-jscript@1.0.4
│ │ ├── babel-plugin-member-expression-literals@1.0.1
│ │ ├── babel-plugin-property-literals@1.0.1
│ │ ├── babel-plugin-proto-to-assign@1.0.4
│ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ ├── babel-plugin-react-display-name@1.0.3
│ │ ├── babel-plugin-remove-console@1.0.1
│ │ ├── babel-plugin-remove-debugger@1.0.1
│ │ ├── babel-plugin-runtime@1.0.7
│ │ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ │ │ └── leven@1.0.2
│ │ ├── babel-plugin-undefined-to-void@1.1.6
│ │ ├── babylon@5.8.35
│ │ ├── bluebird@2.10.2
│ │ ├── convert-source-map@1.2.0
│ │ ├── core-js@1.2.6
│ │ ├─┬ detect-indent@3.0.1
│ │ │ ├── get-stdin@4.0.1
│ │ │ └── minimist@1.2.0
│ │ ├── esutils@2.0.2
│ │ ├── fs-readdir-recursive@0.1.2
│ │ ├── globals@6.4.1
│ │ ├─┬ home-or-tmp@1.0.0
│ │ │ ├── os-tmpdir@1.0.1
│ │ │ └── user-home@1.1.1
│ │ ├─┬ is-integer@1.0.6
│ │ │ └─┬ is-finite@1.0.1
│ │ │   └── number-is-nan@1.0.0
│ │ ├── js-tokens@1.0.1
│ │ ├── json5@0.4.0
│ │ ├─┬ line-numbers@0.2.0
│ │ │ └── left-pad@0.0.3
│ │ ├─┬ output-file-sync@1.1.1
│ │ │ └── xtend@4.0.1
│ │ ├── path-exists@1.0.0
│ │ ├── path-is-absolute@1.0.0
│ │ ├── private@0.1.6
│ │ ├─┬ regenerator@0.8.40
│ │ │ ├─┬ commoner@0.10.4
│ │ │ │ ├─┬ detective@4.3.1
│ │ │ │ │ ├── acorn@1.2.2
│ │ │ │ │ └── defined@1.0.0
│ │ │ │ ├── graceful-fs@4.1.3
│ │ │ │ ├── iconv-lite@0.4.13
│ │ │ │ └── q@1.4.1
│ │ │ ├─┬ defs@1.1.1
│ │ │ │ ├─┬ alter@0.2.0
│ │ │ │ │ └── stable@0.1.5
│ │ │ │ ├── ast-traverse@0.1.1
│ │ │ │ ├── breakable@1.0.0
│ │ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb
│ │ │ │ ├── simple-fmt@0.1.0
│ │ │ │ ├── simple-is@0.2.0
│ │ │ │ ├── stringmap@0.2.2
│ │ │ │ ├── stringset@0.2.1
│ │ │ │ ├── tryor@0.1.2
│ │ │ │ └─┬ yargs@3.27.0
│ │ │ │   ├── camelcase@1.2.1
│ │ │ │   ├─┬ cliui@2.1.0
│ │ │ │   │ ├─┬ center-align@0.1.3
│ │ │ │   │ │ ├─┬ align-text@0.1.4
│ │ │ │   │ │ │ ├─┬ kind-of@3.0.2
│ │ │ │   │ │ │ │ └── is-buffer@1.1.2
│ │ │ │   │ │ │ ├── longest@1.0.1
│ │ │ │   │ │ │ └── repeat-string@1.5.4
│ │ │ │   │ │ └── lazy-cache@1.0.3
│ │ │ │   │ ├── right-align@0.1.3
│ │ │ │   │ └── wordwrap@0.0.2
│ │ │ │   ├── decamelize@1.1.2
│ │ │ │   ├─┬ os-locale@1.4.0
│ │ │ │   │ └─┬ lcid@1.0.0
│ │ │ │   │   └── invert-kv@1.0.0
│ │ │ │   ├── window-size@0.1.4
│ │ │ │   └── y18n@3.2.0
│ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb
│ │ │ ├─┬ recast@0.10.33
│ │ │ │ ├── ast-types@0.8.12
│ │ │ │ └── esprima-fb@15001.1001.0-dev-harmony-fb
│ │ │ └── through@2.3.8
│ │ ├─┬ regexpu@1.3.0
│ │ │ ├── esprima@2.7.2
│ │ │ ├── regenerate@1.2.1
│ │ │ ├── regjsgen@0.2.0
│ │ │ └─┬ regjsparser@0.1.5
│ │ │   └── jsesc@0.5.0
│ │ ├── repeating@1.1.3
│ │ ├── shebang-regex@1.0.0
│ │ ├── slash@1.0.0
│ │ ├── source-map@0.5.3
│ │ ├─┬ source-map-support@0.2.10
│ │ │ └─┬ source-map@0.1.32
│ │ │   └── amdefine@1.0.0
│ │ ├── to-fast-properties@1.0.1
│ │ ├── trim-right@1.0.1
│ │ └── try-resolve@1.0.1
│ ├─┬ babel-jscs@2.0.5
│ │ └─┬ lodash.assign@3.2.0
│ │   ├─┬ lodash._baseassign@3.2.0
│ │   │ └── lodash._basecopy@3.0.1
│ │   ├─┬ lodash._createassigner@3.1.1
│ │   │ ├── lodash._bindcallback@3.0.1
│ │   │ ├── lodash._isiterateecall@3.0.9
│ │   │ └── lodash.restparam@3.6.1
│ │   └─┬ lodash.keys@3.1.2
│ │     ├── lodash._getnative@3.9.1
│ │     ├── lodash.isarguments@3.0.8
│ │     └── lodash.isarray@3.0.4
│ ├─┬ chalk@1.1.1
│ │ ├─┬ ansi-styles@2.2.0
│ │ │ └── color-convert@1.0.0
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ cli-table@0.3.1
│ │ └── colors@1.0.3
│ ├─┬ commander@2.8.1
│ │ └── graceful-readlink@1.0.1
│ ├─┬ escope@3.5.0
│ │ ├─┬ es6-map@0.1.3
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.11
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.4
│ │ │ ├── es6-symbol@3.0.2
│ │ │ └── event-emitter@0.3.4
│ │ ├── es6-weak-map@2.0.1
│ │ └─┬ esrecurse@4.0.0
│ │   └── object-assign@4.0.1
│ ├── esprima@2.5.0
│ ├── estraverse@4.1.1
│ ├── exit@0.1.2
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ └── once@1.3.3
│ ├─┬ htmlparser2@3.8.3
│ │ ├── domelementtype@1.3.0
│ │ ├── domhandler@2.3.0
│ │ ├─┬ domutils@1.5.1
│ │ │ └─┬ dom-serializer@0.1.0
│ │ │   ├── domelementtype@1.1.3
│ │ │   └── entities@1.1.1
│ │ ├── entities@1.0.0
│ │ └── readable-stream@1.1.13
│ ├─┬ js-yaml@3.4.6
│ │ ├─┬ argparse@1.0.6
│ │ │ └── sprintf-js@1.0.3
│ │ ├── esprima@2.7.2
│ │ └── inherit@2.2.3
│ ├─┬ jscs-jsdoc@1.2.0
│ │ ├── comment-parser@0.3.0
│ │ └── jsdoctypeparser@1.2.0
│ ├─┬ jsonlint@1.6.2
│ │ ├── JSV@4.0.2
│ │ └─┬ nomnom@1.8.1
│ │   ├─┬ chalk@0.4.0
│ │   │ ├── ansi-styles@1.0.0
│ │   │ ├── has-color@0.1.7
│ │   │ └── strip-ansi@0.1.1
│ │   └── underscore@1.6.0
│ ├── lodash@3.10.1
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.3
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├── natural-compare@1.2.2
│ ├── pathval@0.1.1
│ ├─┬ prompt@0.2.14
│ │ ├── pkginfo@0.4.0
│ │ ├─┬ read@1.0.7
│ │ │ └── mute-stream@0.0.6
│ │ ├── revalidator@0.1.8
│ │ ├─┬ utile@0.2.1
│ │ │ ├── async@0.2.10
│ │ │ ├── deep-equal@1.0.1
│ │ │ ├── i@0.3.4
│ │ │ ├── ncp@0.4.2
│ │ │ └─┬ rimraf@2.5.2
│ │ │   └── glob@7.0.0
│ │ └─┬ winston@0.8.3
│ │   ├── colors@0.6.2
│ │   ├── cycle@1.0.3
│ │   ├── eyes@0.1.8
│ │   ├── isstream@0.1.2
│ │   ├── pkginfo@0.3.1
│ │   └── stack-trace@0.0.9
│ ├── reserved-words@0.1.1
│ ├── resolve@1.1.7
│ ├─┬ strip-bom@2.0.0
│ │ └── is-utf8@0.2.1
│ ├── strip-json-comments@1.0.4
│ ├─┬ to-double-quotes@1.0.2
│ │ └── get-stdin@3.0.2
│ ├─┬ to-single-quotes@1.0.4
│ │ └── get-stdin@3.0.2
│ ├── vow@0.4.12
│ ├─┬ vow-fs@0.3.4
│ │ ├── glob@4.5.3
│ │ ├── node-uuid@1.4.7
│ │ └── vow-queue@0.4.2
│ └── xmlbuilder@2.6.5
├─┬ mocha@2.4.5
│ ├── commander@2.3.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── supports-color@1.2.0
└─┬ mongodb@2.1.7
  ├── es6-promise@3.0.2
  ├─┬ mongodb-core@1.3.1
  │ ├── bson@0.4.21
  │ └─┬ require_optional@1.0.0
  │   ├── resolve-from@2.0.0
  │   └── semver@5.1.0
  └─┬ readable-stream@1.0.31
    ├── core-util-is@1.0.2
    ├── isarray@0.0.1
    └── string_decoder@0.10.31

$ npm test

> @ test /home/travis/build/urfu-2015/webdev-tasks-2
> mocha test/* && npm run lint

  Check
    Extra credit
      ✓ should check that del (291ms)
      ✓ should check that target insert (197ms)
      ✓ should check that target find equal (107ms)
      ✓ should check that target find not equal (105ms)
      ✓ should check that target find include (102ms)
      ✓ should check that target find not include (102ms)
      ✓ should check that target find lessThan (108ms)
      ✓ should check that target find not lessThan (104ms)
      ✓ should check that target find greatThan (102ms)
      ✓ should check that target find not greatThan (101ms)
      1) should check that target update
      ✓ should check that target remove (125ms)

  11 passing (3s)
  1 failing

  1) Check Extra credit should check that target update:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

npm ERR! Test failed.  See above for more details.

The command "npm test" exited with 1.

Done. Your build exited with 1.